/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
class AppTest {
    @Test void transformMethodWritesToOutputFile() {
        // Arrange.
        Bitmap bitmap = new Bitmap("baldy-8bit.bmp", "test.file.bmp");
        Boolean expectResult = true;
        // Act.
        Boolean actualResult = bitmap.changeImgColor();

        // Assert.
        Assertions.assertEquals(expectResult, actualResult, "Should return true unless throws.");

    }
}
